config/routes.rb
Copycopter::Application.routes.draw do
  namespace :api do
    namespace :v2 do
      resources :projects, :only => [] do
        resources :deploys, :only => [:create]
        resources :draft_blurbs, :only => [:create, :index]
        resources :published_blurbs, :only => [:index]
      end
    end
  end

  resources :projects, :only => [:index, :show] do
    resources :blurbs, :only => [:destroy]
    resources :locales, :only => [:new]
  end

  resources :localizations, :only => [] do
    resources :versions, :only => [:new, :create]
  end

  root :to => 'projects#index'
end

app/views/shared/_flashes.html.erb
<div id='flash'>
  <% [:success, :error, :notice, :failure, :alert].each do |key| -%>
    <% if flash.key?(key) -%>
      <div id='flash_<%= key %>'><p><%=h flash[key] %></p></div>
    <% end -%>
  <% end -%>
</div>

app/views/shared/_footer.html.erb
<div id='footer' class='wrapper'>
  <p>
  <%= link_to 'Report an Issue',
    'http://github.com/copycopter/copycopter-server/issues', 
    :target => "blank" -%>
  </p>
</div>

<div id='clouds'></div>

<div id='ground'>
  <div id='grass'></div>
</div>

app/views/shared/_head.html.erb
<meta charset='utf-8'>
<title>Copycopter</title>
<link rel='fluid-icon' href='/assets/fluid-icon.png'>
<link rel='shortcut icon' href='/favicon.ico'>
<link href='https://fonts.googleapis.com/css?family=PT+Sans&subset=latin' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=PT+Sans:bold&subset=latin' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag 'application' %>
<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico'>
<%= csrf_meta_tag %>

app/views/shared/_header.html.erb
<h1 id='logo'><%= link_to 'Copycopter', root_path %></h1>

<%= yield :button %>

app/views/shared/_javascript.html.erb
<%= javascript_include_tag 'application' %>
<%= yield :javascript -%>

app/views/shared/_locale_dropdown.html.erb
<ul id='locale_dropdown'>
  <li>
    <p class='selected'>
      <%= link_to '#' do -%>
        Locale:
        <span><%= @locale.key %></span>
      <% end -%>
    </p>

    <ul class='menu'>
      <%= yield :locales %>

      <li>
        <%= link_to 'Add a new locale...', new_project_locale_path(@project) %>
      </li>
    </ul>
  </li>
</ul>